'use strict';
/**
 * strategy/engines/revenue-system.js
 * Module 4 (Revenue System Engine): Method + Tone + Platform + Assets + Funnel.
 *
 * Integrates with existing iteration-engine.js (VARIATION_MODES) for tone/method mapping.
 * Platform selection reuses CATEGORY_STYLE_MAP patterns from marketing-memory.js.
 * Core message and funnel architecture are generated by AI (claude-strategy-engine.js).
 */

const { VARIATION_MODES } = require('../../iteration-engine');

// ── Marketing Method Selection ─────────────────────────────────────────────────
// Mapped to iteration-engine.js VARIATION_MODES where applicable
const METHOD_RULES = [
  {
    method:      'direct_response',
    variationMode: 'aggressive',
    label:       'Direct Response (תגובה ישירה)',
    description: 'כאב חזק, הנעה לפעולה, דחיפות — מתאים לקהל "רעב" עם כאב דחוף',
    matches: ({ painScore, marketSkepticism }) =>
      painScore >= 70 && marketSkepticism === 'low',
  },
  {
    method:      'authority_educational',
    variationMode: 'premium',
    label:       'Authority / Educational (סמכות וחינוך)',
    description: 'הסבר, בניית אמון, עומק — מתאים לשוק סקפטי או מוצר מורכב',
    matches: ({ marketSkepticism, productComplexity }) =>
      marketSkepticism === 'high' || productComplexity === 'high',
  },
  {
    method:      'emotional_story',
    variationMode: 'emotional',
    label:       'Emotional / Story (רגשי וסיפור)',
    description: 'הזדהות, סיפור, חיבור — מתאים לכאב אישי ורגשי',
    matches: ({ painType }) =>
      ['fear', 'frustration'].includes(painType),
  },
  {
    method:      'proof_driven',
    variationMode: 'bold',
    label:       'Proof Driven (מבוסס הוכחה)',
    description: 'תוצאות, מספרים, דוגמאות — מתאים לשוק תחרותי עם חוסר אמון',
    matches: ({ competitorCount }) =>
      competitorCount >= 5,
  },
];

function selectMarketingMethod({ painScore, painType, competitorCount, marketSkepticism, productComplexity }) {
  const context = { painScore, painType, competitorCount, marketSkepticism: marketSkepticism || 'medium', productComplexity: productComplexity || 'medium' };
  const matched = METHOD_RULES.find(r => r.matches(context));
  const primary = matched || METHOD_RULES[0];
  const secondary = METHOD_RULES.find(r => r !== primary && r.matches(context)) || METHOD_RULES[1];
  return {
    primary:   { method: primary.method, label: primary.label, description: primary.description, variationMode: primary.variationMode },
    secondary: { method: secondary.method, label: secondary.label, variationMode: secondary.variationMode },
  };
}

// ── Tone Selection ─────────────────────────────────────────────────────────────
const TONE_MAP = {
  direct_response:    { tone: 'direct',      label: 'תקיף וישיר' },
  authority_educational: { tone: 'authority', label: 'סמכותי ומקצועי' },
  emotional_story:    { tone: 'empathetic',  label: 'אמפתי ומחבר' },
  proof_driven:       { tone: 'provocative', label: 'פרובוקטיבי עם הוכחות' },
};

function selectTone(primaryMethod) {
  return TONE_MAP[primaryMethod] || { tone: 'direct', label: 'תקיף וישיר' };
}

// ── Platform Selection ─────────────────────────────────────────────────────────
const PLATFORM_RULES = [
  { platform: 'tiktok',    score: (ctx) => ctx.ageRange === 'young' ? 30 : 10 },
  { platform: 'instagram', score: (ctx) => (ctx.visual || ctx.lifestyle) ? 25 : 15 },
  { platform: 'facebook',  score: (ctx) => ctx.ageRange === 'mature' ? 25 : 18 },
  { platform: 'google',    score: (ctx) => ctx.searchIntent ? 28 : 12 },
  { platform: 'youtube',   score: (ctx) => ctx.productComplexity === 'high' ? 20 : 8 },
];

function selectPlatforms({ segments, productType, painType, competitorPlatforms }) {
  // Infer context from available data
  const ctx = {
    ageRange:          segments.some(s => /25|30|18/.test(s)) ? 'young' : 'mature',
    visual:            ['coaching','service'].includes(productType),
    lifestyle:         false,
    searchIntent:      painType === 'pain' || painType === 'frustration',
    productComplexity: productType === 'saas' || productType === 'coaching' ? 'high' : 'medium',
  };

  // Boost platforms used by competitors
  const competitorBoost = {};
  (competitorPlatforms || []).forEach(p => { competitorBoost[p] = (competitorBoost[p] || 0) + 5; });

  const scored = PLATFORM_RULES.map(r => ({
    platform: r.platform,
    score:    r.score(ctx) + (competitorBoost[r.platform] || 0),
  })).sort((a, b) => b.score - a.score);

  return {
    primary:   scored[0].platform,
    secondary: scored.slice(1, 3).map(p => p.platform),
    all:       scored,
  };
}

// ── Asset System ──────────────────────────────────────────────────────────────
const ASSET_RULES = {
  service:  { required: ['ad_video', 'landing_page', 'whatsapp_message'], optional: ['lead_magnet', 'case_study'] },
  coaching: { required: ['ad_video', 'sales_page', 'lead_magnet'], optional: ['webinar_script', 'email_sequence'] },
  course:   { required: ['ad_creative', 'landing_page', 'lead_magnet'], optional: ['webinar_script', 'email_sequence', 'sales_page'] },
  saas:     { required: ['ad_creative', 'landing_page', 'onboarding_email'], optional: ['demo_video', 'case_study'] },
};

function buildAssetSystem(productType) {
  return ASSET_RULES[productType] || ASSET_RULES.course;
}

// ── Funnel Skeleton (stages, filled by AI) ────────────────────────────────────
function buildFunnelSkeleton(method, platforms) {
  const trafficSource = method === 'direct_response' ? `תנועה ממומנת ב-${platforms.primary}` : `תנועה אורגנית + ממומנת`;
  return {
    traffic_source:    trafficSource,
    hook_strategy:     null,  // AI fills
    content_type:      null,  // AI fills
    trust_builder:     null,  // AI fills
    offer_structure:   null,  // AI fills
    conversion_method: null,  // AI fills
    follow_up:         null,  // AI fills
  };
}

// ── Main ──────────────────────────────────────────────────────────────────────
function runRevenueSystemEngine({ selectedPain, painType, painScore, competitorMessages, productType, segments, opportunityZones }) {
  const competitorCount    = competitorMessages.length;
  const competitorPlatforms= [...new Set(competitorMessages.flatMap(c => c.platforms || []))];

  const method    = selectMarketingMethod({ painScore, painType, competitorCount, productComplexity: productType === 'saas' ? 'high' : 'medium' });
  const tone      = selectTone(method.primary.method);
  const platforms = selectPlatforms({ segments, productType, painType, competitorPlatforms });
  const assets    = buildAssetSystem(productType);
  const funnel    = buildFunnelSkeleton(method.primary.method, platforms);

  return {
    method,
    tone,
    platforms,
    assets,
    funnel,
    // Filled by AI:
    coreMessage:   null,
    angles:        [],
    targetCustomer: null,
  };
}

module.exports = { runRevenueSystemEngine, selectMarketingMethod, selectTone, selectPlatforms, buildAssetSystem, VARIATION_MODES };
